import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins, EB_Garamond } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Include your fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&family=Garamond&display=swap"
          rel="preload"
          as="font"
          type="font/woff2"
        />
      </head>
      <body
        className={`${poppins.variable} ${garamond.variable} antialiased font-primary`}
      >
        {children}
      </body>
    </html>
  );
}
